// <auto-generated />
/// <summary>
/// ^^Disables auto formatting because disabling settings for this specific file in
/// editorconfig seems not to work.
/// </summary>

//System usings
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Diagnostics;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Reflection;
global using global::System.Text;
global using global::System.Threading;
global using global::System.Threading.Tasks;

//Ours
global using global::Keysharp.Builtins;
global using global::Keysharp.Components.Scripting;
global using global::Keysharp.Internals.Scripting;
global using global::Keysharp.Language;
global using global::Keysharp.Runtime;

//Third party/UI
#if WINDOWS
	global using global::ScintillaNET;
	global using global::System.Drawing;
	global using global::System.Windows.Forms;
#else
	global using global::Eto.Drawing;
	global using global::Eto.Forms;
#endif

//Aliases
#if WINDOWS
	global using UITimer = System.Windows.Forms.Timer;
#endif