using Keysharp.Runtime;

namespace Keysharp.Builtins
{
	internal interface I__Enum
	{
		public KeysharpFunc __Enum(object count);
	}

	/// <summary>
	/// The base class of every script object. The C# type is named <c>KeysharpObject</c> because
	/// <c>Object</c> is <see cref="System.Object"/>; scripts see it as <c>Object</c> via
	/// <see cref="UserDeclaredNameAttribute"/>.
	/// </summary>
	[UserDeclaredName("Object")]
	public class KeysharpObject : Any
	{
		public KeysharpObject(params object[] args) : base(args) { }

		/// <summary>
		/// Creates a new <see cref="KeysharpObject"/> object.
		/// This can be called manually by the script or be generated by the parser
		/// for object literal construction like:
		/// val := { one : 1 }
		/// Note that the map must be case insensitive so that property lookups like:
		/// val.one and val.One both work.
		/// </summary>
		/// <param name="args">The optional data to initialize the <see cref="KeysharpObject"/> with. This can be:
		///     An object[] of key,value pairs.
		/// </param>
		/// <returns>A new <see cref="KeysharpObject"/> object.</returns>
		// Constructing a user class relays its arguments through Class.Call to __New, so a named argument names one
		// of __New's parameters rather than one of this method's -- the container rides the tail of args and binds
		// where __New's signature is known.
		public static object staticCall(object @this, params object[] args)
		{
			if (@this is not Class cls)
				return Errors.TypeErrorOccurred(@this, typeof(Class));

			var kso = cls.Call(args) as KeysharpObject;
			if (kso.type != typeof(KeysharpObject))
				return kso;

			// `Object("k", 1)` takes name/value PAIRS; `Object(k: 1)` says the same thing as a named argument, so
			// the names are read as pairs too, making the call agree with the `{k: 1}` literal.
			var positional = NamedArgBinder.SplitAt(args, out var named);

			// A dangling name would otherwise be dropped without a trace.
			if ((positional & 1) != 0)
				return Errors.ValueErrorOccurred("Object() requires an even number of name/value parameters.");

			for (var i = 0; i < positional; i += 2)
				DefineOne(kso, args[i].ToString(), args[i + 1]);

			if (named != null)
				foreach (var (name, value) in named.Entries())
					DefineOne(kso, name, value);

			return kso;
		}

		private static void DefineOne(KeysharpObject kso, string name, object value)
		{
			if (name.Equals("base", StringComparison.OrdinalIgnoreCase))
				kso.SetBaseInternal((Any)value);
			else
				kso.DefinePropInternal(name, new OwnPropsDesc(kso, value));
		}

		/// <summary>
		/// Return a cloned copy of the object.
		/// Just calling MemberwiseClone() is sufficient to clone all of the properties as well
		/// as the OwnProps object op.
		/// </summary>
		/// <returns>A cloned copy of the object.</returns>
		public new object Clone()
		{
			return MemberwiseClone();
		}

		public static object DefineProp(object @this, object name, object descriptor) => Objects.DefineProp(@this, name, descriptor);

		public static object DeleteProp(object @this, object name) =>
			@this is Any target ? target.DeleteOwnPropInternal(name.As()) : Errors.TypeErrorOccurred(@this, typeof(Any));

		public static object GetOwnPropDesc(object @this, object name)
		{
			if (@this is not Any obj)
				return Errors.TypeErrorOccurred(@this, typeof(Any));

			var nameVal = name.As();

			if (obj.op != null && obj.op.TryGetValue(nameVal, out var dynProp))
			{
				return dynProp.GetDesc();
			}

			try
			{
				var val = Script.GetPropertyValue(obj, nameVal);
				return KeysharpObject.staticCall(TheScript.Vars.Statics[typeof(KeysharpObject)], ["value", val]);
			}
			catch
			{
			}

			return Script.CompatReturnsUnsetForMissing ? null
				: Errors.PropertyErrorOccurred($"Object did not have an OwnProp named {nameVal}.");
		}

		public static object __Ref(object @this, object name, params object[] args)
		{
			var ctorArgs = new object[(args?.Length ?? 0) + 2];
			ctorArgs[0] = @this;
			ctorArgs[1] = name;
			if (args != null && args.Length > 0)
				System.Array.Copy(args, 0, ctorArgs, 2, args.Length);
			return PropRef.staticCall(TheScript.Vars.Statics[typeof(PropRef)], ctorArgs);
		}

		public static long HasOwnProp(object @this, object name)
		{
			// Reached with a primitive receiver through the free function ObjHasOwnProp, which — unlike the method
			// form — has no prototype lookup to fail first.
			if (@this is not Any obj)
				return (long)Errors.TypeErrorOccurred(@this, typeof(Any), 0L);

			var nameVal = name.As();

			if (obj.op != null && obj.op.ContainsKey(nameVal))
				return 1L;

			return Reflections.FindOwnProp(obj.GetType(), nameVal) ? 1L : 0L;
		}

		public static long OwnPropCount(object @this)
		{
			// Reached with a primitive through the free function ObjOwnPropCount, which — unlike the method form —
			// has no prototype lookup to fail first.
			if (@this is not Any obj)
				return (long)Errors.TypeErrorOccurred(@this, typeof(Any), 0L);

			var ct = 0L;
			var type = obj.GetType();
			var isMapOnly = type == typeof(Map);

			if (obj.op != null)
				ct += obj.op.Count;

			if (!isMapOnly)
			{
				_ = Reflections.FindAndCacheProperty(type, "", -1);
				ct += Reflections.OwnPropCount(type);
			}

			return ct;
		}

		/// <summary>
		/// Enumerates this object's own properties, matching AutoHotkey's OwnProps().
		/// <para>
		/// Takes no arguments: how many values an iteration yields is decided by the for-loop's variable count,
		/// which <see cref="Enumerator.Call"/> reads from the number of VarRefs it is handed and passes to
		/// <c>Advance</c>, so a one-variable loop never evaluates a property getter and never skips a property.
		/// A C# <c>foreach</c> has no such count and falls back to <see cref="Enumerator.Count"/>, which is why
		/// this builds a two-value enumerator; there is no setting for a caller to make here.
		/// </para>
		/// </summary>
		public static object OwnProps(object @this)
		{
			if (@this is not Any obj)
				return Errors.TypeErrorOccurred(@this, typeof(Any));

			var props = new Dictionary<object, object>();

			if (obj.op != null)
			{
				foreach (var kv in obj.op)
				{
					if (kv.Key == "__Static") //This throws if the value is tried to access because "this" is passed
						continue;

					props[kv.Key] = kv.Value;
				}
			}

			return OwnPropsEnumeration.CreateEnumerator(obj, props, true);
		}

		[PublicHiddenFromUser]
		public override Any Base
		{
			get => _base;
			set => Objects.ObjSetBase(this, value);
		}
	}
}
