using Antlr4.Runtime.Misc;
using Keysharp.Core.Scripting.Script;

namespace Keysharp.Core.Common.ObjectBase
{
	internal interface I__Enum
	{
		public IFuncObj __Enum(object count);
	}

	public class KeysharpObject : Any
	{
		public KeysharpObject(params object[] args) : base(args) { }
		public KeysharpObject(bool skipLogic) : base(skipLogic) { }

		public static object Call(object @this, params object[] args) => FastCtor.Call(@this.GetType(), args);

		/// <summary>
		/// Creates a new <see cref="KeysharpObject"/> object.
		/// This can be called manually by the script or be generated by the parser
		/// for object literal construction like:
		/// val := { one : 1 }
		/// Note that the map must be case insensitive so that property lookups like:
		/// val.one and val.One both work.
		/// </summary>
		/// <param name="args">The optional data to initialize the <see cref="KeysharpObject"/> with. This can be:
		///     An object[] of key,value pairs.
		/// </param>
		/// <returns>A new <see cref="KeysharpObject"/> object.</returns>
		public override object __New(params object[] args)
		{
			var count = (args.Length / 2) * 2;

			for (var i = 0; i < count; i += 2)
			{
				var name = args[i].ToString();
				if (name.Equals("base", StringComparison.OrdinalIgnoreCase))
					SetBaseInternal((Any)args[i + 1]);
				else
					DefinePropInternal(name, new OwnPropsDesc(this, args[i + 1]));
			}

			return this;
		}

		/// <summary>
		/// Return a cloned copy of the object.
		/// Just calling MemberwiseClone() is sufficient to clone all of the properties as well
		/// as the OwnProps object op.
		/// </summary>
		/// <returns>A cloned copy of the object.</returns>
		public new object Clone()
		{
			return MemberwiseClone();
		}

		public object DefineProp(object obj0, object obj1) => Objects.ObjDefineProp(this, obj0, obj1);

		public object DeleteProp(object obj) => DeleteOwnPropInternal(obj.As());

		public object GetOwnPropDesc(object obj)
		{
			var name = obj.As();

			if (op != null && op.TryGetValue(name, out var dynProp))
			{
				return dynProp.GetDesc();
			}

			try
			{
				var val = Script.GetPropertyValue(this, name);
				return new KeysharpObject(["value", val]);
			}
			catch
			{
			}

			return Errors.PropertyErrorOccurred($"Object did not have an OwnProp named {name}.");
		}

		public long HasOwnProp(object obj)
		{
			var name = obj.As();

			if (op != null && op.ContainsKey(name))
				return 1L;

			return Reflections.FindOwnProp(GetType(), name.ToLower()) ? 1L : 0L;
		}

		public long OwnPropCount()
		{
			var ct = 0L;
			var isMapOnly = GetType() == typeof(Map);

			if (op != null)
				ct += op.Count;

			if (!isMapOnly)
			{
				_ = Reflections.FindAndCacheProperty(GetType(), "", -1);
				ct += Reflections.OwnPropCount(GetType());
			}

			return ct;
		}

		public object OwnProps(object getValues = null)
		{
			var vals = getValues.Ab(true);
			var props = new Dictionary<object, object>();

			if (op != null)
			{
				foreach (var kv in op)
				{
					if (kv.Key == "__Static") //This throws if the value is tried to access because "this" is passed
						continue;

					props[kv.Key] = kv.Value;
				}
			}

			return new OwnPropsIterator(this, props, vals).fo;
		}

		public virtual void PrintProps(string name, StringBuffer sb, ref int tabLevel)
		{
			var fieldType = GetType().Name;
			var opi = (OwnPropsIterator)((FuncObj)OwnProps(true)).Inst;
			var indent = new string('\t', tabLevel);

			if (name.Length == 0)
				_ = sb.AppendLine($"{indent} ({fieldType})");
			else
				_ = sb.AppendLine($"{indent}{name}: ({fieldType})");

			tabLevel++;
			indent = new string('\t', tabLevel);

			while (opi.MoveNext())
			{
				var (propName, val) = opi.Current;
				fieldType = val != null ? val.GetType().Name : "";

				if (val != this && val is KeysharpObject kso2)//Check against this to prevent stack overflow.
				{
					kso2.PrintProps(propName.ToString(), sb, ref tabLevel);
				}
				else if (val != null)
				{
					if (val is string vs)
					{
						var str = "\"" + vs + "\"";//Can't use interpolated string here because the AStyle formatter misinterprets it.
						_ = sb.AppendLine($"{indent}{propName}: {str} ({fieldType})");
					}
					else
						_ = sb.AppendLine($"{indent}{propName}: {val} ({fieldType})");
				}
				else
					_ = sb.AppendLine($"{indent}{propName}: null");
			}

			tabLevel--;
		}

		[PublicHiddenFromUser]
		public override Any Base
		{
			get => _base;
			set => Objects.ObjSetBase(this, value);
		}
	}
}