// <auto-generated />
/// <summary>
/// ^^Disables auto formatting because disabling settings for this specific file in
/// editorconfig seems not to work.
/// </summary>

//System usings
global using global::System;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Generic;
global using global::System.Diagnostics;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Pipes;
global using global::System.Linq;
global using global::System.Net;
global using global::System.Net.Sockets;
global using global::System.Reflection;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.InteropServices;
global using global::System.Security.Principal;
global using global::System.Text;
global using global::System.Threading;
global using global::System.Threading.Tasks;

#if WINDOWS
	global using global::System.Drawing;
	global using global::System.Windows.Forms;
#else
	global using global::Eto.Drawing;
	global using global::Eto.Forms;
#endif

//Our usings
global using global::Keysharp.Builtins;
global using global::Keysharp.Builtins.COM;
global using global::Keysharp.Compilation;
global using global::Keysharp.Components.Scripting;
global using global::Keysharp.Components.Scripting.Compiler;
global using global::Keysharp.Components.Scripting.Parser;
global using global::Keysharp.Internals;
global using global::Keysharp.Internals.AppleEvents;
global using global::Keysharp.Internals.Audio;
global using global::Keysharp.Internals.Events;
global using global::Keysharp.Internals.ExtensionMethods;
global using global::Keysharp.Internals.Images;
global using global::Keysharp.Internals.Input;
global using global::Keysharp.Internals.Input.Hooks;
global using global::Keysharp.Internals.Input.Keyboard;
global using global::Keysharp.Internals.Invoke;
global using global::Keysharp.Internals.Os;
global using global::Keysharp.Internals.Scripting;
global using global::Keysharp.Internals.Strings;
global using global::Keysharp.Internals.Threading;
global using global::Keysharp.Internals.Window;
global using global::Keysharp.Language;
global using global::Keysharp.Parsing;
global using global::Keysharp.Parsing.Lexing;
global using global::Keysharp.Runtime;

#if WINDOWS
	global using global::Keysharp.Internals.Input.Hooks.Windows;
	global using global::Keysharp.Internals.Input.Windows;
	global using global::Keysharp.Internals.Os.Windows;
	global using global::Keysharp.Internals.Window.Windows;
	global using global::Keysharp.Main;
	global using MessageFilter = Keysharp.Internals.Window.Windows.MessageFilter;
#else
	global using global::Keysharp.Internals.Input.Hooks.Unix;
	global using global::Keysharp.Internals.Input.Unix;
	global using global::Keysharp.Internals.Window.Unix;
#endif

#if OSX
	global using global::Keysharp.Internals.Input.MacOS;
	global using global::Keysharp.Internals.Window.MacOS;
	global using AppKit = MonoMac.AppKit;
#elif LINUX
	global using global::Keysharp.Internals.Input.Hooks.Linux;
	global using global::Keysharp.Internals.Input.Linux;
	global using global::Keysharp.Internals.Linux;
	global using global::Keysharp.Internals.Window.Linux.Wayland;
	global using global::Keysharp.Internals.Window.Linux.X11;
	global using global::Keysharp.Internals.DBus;
#endif

//Third party.
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.CodeAnalysis.CSharp.Syntax;
global using global::NUnit.Framework;

#if LINUX
	global using global::Tmds.DBus.Protocol;
#endif

//Static
global using static global::Keysharp.Builtins.Accessors;
global using static global::Keysharp.Builtins.Ks;
global using static global::Keysharp.Language.Keywords;

//Aliases
global using Platform = Keysharp.Internals.Platform;