<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPublishable>false</IsPublishable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <NoWin32Manifest>true</NoWin32Manifest>
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
		<TargetFramework>net10.0-windows</TargetFramework>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
		<TargetFramework>net10.0</TargetFramework> <!-- net10.0 required so VSCode debugger doesn't crash on exceptions -->
		<DefineConstants>$(DefineConstants);LINUX</DefineConstants>
		<LangVersion>14.0</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
		<TargetFramework>net10.0</TargetFramework>
		<DefineConstants>$(DefineConstants);OSX</DefineConstants>
		<LangVersion>14.0</LangVersion>
	</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;LEGACY</DefineConstants>
    <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
		<DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(DefineConstants);LINUX</DefineConstants>
		<DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(DefineConstants);OSX</DefineConstants>
    <NoWarn>1701;1702;8981;0164;8974</NoWarn>
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);TRACE;LEGACY</DefineConstants>
    <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
		<DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(DefineConstants);LINUX</DefineConstants>
		<DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(DefineConstants);OSX</DefineConstants>
    <NoWarn>1701;1702;8981;0164;8974</NoWarn>
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Keysharp.Core\Keysharp.Core.csproj" />
	<ProjectReference Include="..\Keysharp.Components\Scripting\Compiler\Keysharp.Components.Scripting.Compiler.csproj" />
  </ItemGroup>
</Project>
